name: offroad-trip
channels:
  - conda-forge
  - esri
dependencies:
  - python=3.11
  - flask
  - flask-cors
  - flask-wtf
  - flask-migrate
  - flask-sqlalchemy
  - geopandas
  - pandas
  - numpy
  - gunicorn
  - gevent
  - werkzeug
  - requests
  - rasterio
  - rasterstats
  - retrying
  - arcgis=2.3.1
  - jupyterlab
  - pyproj
  - shapely
  - fiona
  - pip
  - pip:
      - wtforms
